### ISSUE TITLE
Make `run_site_selection()` more user-friendly

### ISSUE THREAD

**Issue by ConnectedSystems** [open-AIMS/ADRIA.jl#324]
Raising new issue continuing on discussions re [this commit](https://github.com/open-AIMS/ADRIA.jl/commit/65197a3e66e7af4f544411eefe8706523e18b7e1#commitcomment-105303167)

This is also relevant to #252.

Currently `run_site_selection()` requires the user to do a lot of gymnastics to get a usable list of deployment locations.
A small aside: (and as raised previously) the naming should also move away from the "sites" paradigm so it is agnostic to the reef/site/cluster definitions.

The approach I've adopted for this iteration is to fix a few deployment options:

```julia
# TODO: Function that accepts a splatted list of criteria => value pairs to do the below
#       in a single function call. 
# Only use VIKOR
ADRIA.fix_factor!(dom, :guided, 3)

# Always seed (half million each enhanced species)
ADRIA.fix_factor!(dom, :seed_TA, Int64(5e5))
ADRIA.fix_factor!(dom, :seed_CA, Int64(5e5))

# Never fog/shade
ADRIA.fix_factor!(dom, :SRM, 0.0)
ADRIA.fix_factor!(dom, :fogging, 0.0)

# Spread locations around
ADRIA.fix_factor!(dom, :use_dist, 1)
ADRIA.fix_factor!(dom, :dist_thresh, 0.1)
```

Then run the selection process with 128 - 1024 criteria combinations and picking out locations that were ranked the most times for a given rank position.

For example:

Rank 1: The location that was ranked No. 1 the most times
Rank 2: The location that was ranked No. 2 the most times
etc. etc.

I am seeing the same sites being selected regardless of what `dist_thresh` is set to.

![image](https://user-images.githubusercontent.com/4075136/226514384-187c6216-171f-4465-b2e5-46335b0762e9.png)

@Rosejoycrocker wondered what the effect of the `top_n` criteria is. 
As described above, I'm doing a "first past the post" style voting/ranking.

`top_n` ranges from 5 to 50, and Sobol' sampling guarantees an equi-distributed sample.
Is it that low values of `top_n` are biasing results? i.e., different locations become highly ranked with increasing `top_n` such that there is greater consensus with lower values of `top_n`?

Ideally the process below should be hidden away from the user.

```julia
# Target priority sites (this functionality is not yet in `Main`)
# Currently using site indexes, but should use their named IDs instead.
subset_of_sites = findall((dom.site_data.size_group .== 1) .& (dom.site_data.moore_region .== true))
ranks = ADRIA.run_site_selection(dom, scens, sum_cover, area_to_seed, ts; target_seed_sites=subset_of_sites')

# `ranks` currently contains "0" to indicate locations that were not considered.
# This should be set to `N locations + 1` instead. `missing` (as used below) might be a good idea too
# although it complicates processing slightly (also seen below).
seed_ranks = convert(Matrix{Union{Float64,Missing}}, ranks[:, :, 2])
replace!(seed_ranks, 0.0 => missing)

# Quick and dirty collation, there's a better way of doing this
deployment_site_idxs = []
deployment_site_ranks = []
for site_num in 1:dom.sim_constants.n_site_int
    locs = [findfirst(==(Float64(site_num)), skipmissing(sr)) for sr in eachrow(seed_ranks)]
    sorted_locs = sort(countmap([l for l in locs if !isnothing(l)]), byvalue=true, rev=true)

    site_idx = collect(keys(sorted_locs))[1]
    i = 1
    while site_idx ∈ deployment_site_idxs
        i += 1
        site_idx = collect(keys(sorted_locs))[i]
    end

    push!(deployment_site_idxs, collect(keys(sorted_locs))[i])
    push!(deployment_site_ranks, collect(values(sorted_locs))[i])
end
```

**Comment by Rosejoycrocker** [comment]
Hi Takuya, if I wanted to have a look at the distances matrix, what branch would I look at? It's hard to answer your dist_thresh question without having a closer look. It would all depend on the distribution of distances. dist_thresh = 0.9 is a more relaxed distance filter than 0.1, but it could just be that the most frequently selected top ranked sites are sufficiently far apart by both measures. Top_n increases the set of sites you look at when looking to replace sites too close together. So having top_n too large may mean worse results, because lesser ranked sites are acceptible when finding sites sufficiently far apart. But top_n is only the upper bound- if sites are found to be sufficiently far apart within the top 10 but top_n is 50, the final selection will look the same as if topn_n was 10, if that makes sense? I recognise this is complicated for analysis , which is why I'd like to move to a gradient cuttoff - a variable which limits the decrease in aggregate value of criteria to be no  greater than x when replacing sites which are too close.

**Comment by ConnectedSystems** [comment]
> Top_n increases the set of sites you look at when looking to replace sites too close together. So having top_n too large may mean worse results, because lesser ranked sites are acceptible when finding sites sufficiently far apart.

Could you draw a diagram for me? I'm not sure if I understand 100% how this works but conceptually, shouldn't it just ignore the lower ranked sites within the calculated buffer and select from the remaining?

Note also that you're working with centroids - I'm happy for now to just accept it as a limitation but just so we're on the same page.

Here's an example illustrating the issue (and showcasing my skills with MS Paint)

![image](https://user-images.githubusercontent.com/4075136/226767764-3015cf89-3c34-481e-879f-180777669ca9.png)

If I understand correctly, "A" would get selected over "B" even though an area larger than "B" is actually closer to the highly ranked site.

**Comment by Rosejoycrocker** [comment]
What are the ranks of the sites in your diagram?

Here's a little picture (screenshot from powerpoint sorry :'D)
- sites are ordered by rank, and only the top n of the most highly ranked are considered when replacing sites due to being too close. top_n in the diagram is 9.
- in the diagram, numbers are ranks. Red circles mean the current selection. 
- sites ranked 1 and 4 are identified as too close, so 4 is swapped out for 6, the next highest ranking site within the top_n.

![site_swapping](https://user-images.githubusercontent.com/56939532/226770876-d0d2ffa9-0678-4aab-9c08-eab2c245f036.PNG)

**Comment by ConnectedSystems** [comment]
> What are the ranks of the sites in your diagram?

The reef with the black centroid is a "highly ranked" site, B is a reef that is deemed "too close" so hypothetically it will get replaced by "A", because its centroid is further away based on some threshold.

**Comment by ConnectedSystems** [comment]
> So B in your diagram has also been selected as in the top 5 (ie initial selection for intervention?).

Yes.

> only the top n of the most highly ranked are considered

Oh okay, I understand now.

To be honest I think this is complicating things.

My approach would be:
1. Determine ranks as you currently do
2. Collect ids of any location that is too close to the highest `N` locations
2b. If "highly ranked" locations are too close, get the id of the lower ranked one (otherwise, exit here)
3. Filter out the collected ids
4. Select from the list of remaining ids

If needed, repeat from 2 until locations are sufficiently spread or there are no sites left.
Then there's no need for a `top_n` factor.

**Comment by Rosejoycrocker** [comment]
Fair enough, I'll get rid of it in #252. I put it in mostly as security to avoid sorting through too many sites and adding compute time, but I can see how it complicates things.

**Comment by ConnectedSystems** [comment]
> Ok sounds good, I'll wait for resolving https://github.com/open-AIMS/ADRIA.jl/issues/252 to deal with dist_thresh and top_n rather than looking into your branch. I'm holding off on this until the meeting on thurs though.

I don't have any notifications of changes/addition to #252 so I assume you've been working on a separate doc. Look forward to discussing the spec on Thursday then.

**Comment by Rosejoycrocker** [comment]
The only notifications of changes you would have recived would have been prior to this email below. I've left it for now because you asked me not to work on it until we had spoken about it, as in the email below :
"

Hi Rose,

It seems we've hit another bout of miscommunication.

I've noticed that you've started working on code changes for the MCDA before we had a chance to have a discussion as I asked (during the team meeting Thursday about two weeks ago), and you're now in the middle of changing things in response to our exchange on Friday.

I want to stress that the MCDA component is a critical piece of the infrastructure and changes have to be carefully thought out at this stage, otherwise you'll be making tweaks here and there ad nauseum.
I'm a fan of iterative development but we're not there yet for this.

Please hold off working on code for now, at least until we're both comfortable with the initial structure.
I'll respond on GitHub, but keep in mind we've had discussions re changes to the MCDA component sprinkled across other PRs, issues, emails and on Zoom/Teams that is relevant to this.
For example, I'm still not 100% convinced we need the DMCDA_vars type.


Regards,

Takuya
"

I have however, looked into integration of JMcDM for discussion tomorrow.

**Comment by ConnectedSystems** [comment]
I asked that you not work on changing code, I didn't mean to stop working on designing a proposed set of changes.

**Comment by ConnectedSystems** [comment]
Hi Rose

If you recall, we spoke about setting up an issue for this discussion. I assumed you wanted to co-opt #252 for this purpose given the wording used [here](https://github.com/open-AIMS/ADRIA.jl/issues/252#issuecomment-1471292330).

As I mentioned in prior discussions:
- Conceptually, what are the necessary changes to address #252
- Provide examples of possible implementation approaches (with pseudo-code, diagrams, or other as appropriate)
- Detail what implications the proposed changes have on other parts of ADRIA. Ideally with proposals to address or mitigate any adverse effects those changes may have. Detail with pseudo-code or diagrams. Identify which changes are blockers (i.e., they need to be addressed before the current proposal can move forward), a priority (we can work with how things are but they need to be changed later), or if they can be done as part of this proposed change.
- Detail how a user (where user is defined as someone with 1-2 years of programming experience) is expected to use any user-facing functionality (if relevant). Give usage examples e.g., with pseudo-code.
- Using separate scripts, investigate appropriateness of any proposed solutions, particularly if they involve the adoption of an external package (e.g., what impact does it have on performance? Is any performance degradation acceptable? For third-party packages, does it actually offer the capability we want in an appropriate way?)

The goal here is to identify any implementation issues or pain points as much as possible and have these resolved **before** writing any code/making changes. I've already commented on some aspects to this in #252, so I would expect those to be considered as this spec evolves.

If you prefer to do this in a Word doc, that's fine as well.

**Comment by Rosejoycrocker** [comment]
Ok, thanks, I'll add to issue #252. I know you've mentioned some of these, but I think I thought I had them covered in the issue I set up. Obviously this is something more detailed. I've not done this kind of development before, so I'm sorry for the confusion and back-and-forth. The dotpoints are helpful, I'll try and write something for each of them.
