### ISSUE TITLE
Checking centrality is correctly calculated

### ISSUE THREAD

**Issue by Rosejoycrocker** [open-AIMS/ADRIA.jl#329]
Issues with connectivity criteria in the ReefMod site selection suggest potential problems with how centrality is calculated in ADRIA currently. This thread adresses this by comparison to the original Matlab code and discussion with @KRNA01.

Comparing the Julia and Matlab versions, it seems ADRIA the Julia version (ADRIA.jl) had originally used in degree and out degree centrality as in the Matlab version, but this was changed to betweeness centrality and the inverse katz centrality: https://github.com/open-AIMS/ADRIA.jl/blob/77d8b3c664d59b0ba424aaaf3947987b6eaae292/src/sites/connectivity.jl#L141-L160

I recall there being some discussion on centrality measures and which were most descriptive for site selection purposes, which prompted the change. Katz centrality measures the relative "influence" of a node within a network via the total number of connections between each pair of nodes: https://en.wikipedia.org/wiki/Katz_centrality .  I'm not sure why we use 1-Katz_centrality, maybe @ConnectedSystems remembers. I assume it is because it is used as the alternative to out degree centrality but I think 1-Katz_centrality would give a measure of the total number of connections between all sites but the two involved?... The alternative used for in degree centrality is betweenness centrality, which measures the number of shortest paths between nodes that pass through each node : https://en.wikipedia.org/wiki/Betweenness_centrality .

The other key difference between the Matlab and Julia code for connectivity is that the Julia code does not use the digraph edge weights - the weights are commented out with the note that "commented out as ew_base are all equally weighted anyway". Some questions for @KRNA01 
- Should we be using the area and coral cover as the the edge weights for the connectivity matrix before calculating the digraph and centrality? I can't see where this is done in the Matlab code other than where the edge weights are extracted: 

https://github.com/open-AIMS/ADRIA_repo/blob/bc29474555015b88fa0a10f7f935408f0b4f0e76/ADRIAfunctions/siteConnectivity.m#L190

 , but there is no reference to site area or coral cover.
- Are the new centrality measures suitable? They take into account more of the network structure than the simplistc in-degree and out-degree centrality, but thought I'd check.

**Comment by KRNA01** [comment]
From what I can tell, we need to verify that TP_base used in the MCDA are transition probabilities (from eReefs) multiplied by coral cover and reef area.  These are the estimates of connection strengths (edge weights) that account for the amount of corals at each source node.  

Suggested steps: 
1. go to where TP_base is produced and verify that the above is true.
2. make sure that we don't double multiply when we need TP_base in recruitment calculations

**Comment by Rosejoycrocker** [comment]
Thanks Ken, I'll look into this this afternoon. To clarify - does this mean TP_base needs to be multiplied by area and coral cover every time step, as coral cover varies?

**Comment by KRNA01** [comment]
Ideally, but I realise this would create an overhead. Would be great if we could check with @ConnectedSystems 
Even if we use initial coral cover only, it would be better than not using any coral cover.

**Comment by Rosejoycrocker** [comment]
Thanks, I'll check the code and let you know how it is being done currently. Then we can discuss any potential changes with Takuya.

**Comment by Rosejoycrocker** [comment]
Hi @KRNA01, so I checked and as far as I can see, TP_base is loaded from Barbara and Chinenye's files without multiplying by coral cover and area and then set as a constant for a particular Domain. So there's no double multiplying but we 'll have to discuss how to implement the multiplication prior to caluclating in coming centrality and out going centrality (or their equivalents in ADRIA.jl). I can't speak for Takuya, but I believe because TP_base is constant a cache is used to pass the TP_base data to each scenario run efficiently. Due to this we'll have to think carefully about how to implement without reducing efficiency too much. We can discuss when Takuya returns.

**Comment by KRNA01** [comment]
Hi @Rosejoycrocker - this is good info - thank you.

@ConnectedSystems, looks like connectivity in MCDAs are not informed by connection strengths - i.e. transition probability of larvae times coral abundance.  Suggest we update such that TP_base is in the first instance multiplied by reef (or site) area and total relative coral cover to produce an estimates of connection strength.  Centrality can then be calculated using the updated connectivity matrix.  We can normalise to max strengths if we need to in the MCDA

**Comment by ConnectedSystems** [comment]
Hello,

@Rosejoycrocker as I mentioned, the ReefMod related work was done on the `ADRIA-ReefMod` branch.


> I'm not sure why we use 1-Katz_centrality
> I assume it is because it is used as the alternative to out degree centrality

This should have been for in-degree centrality - what was there is a bug. But the inverse Katz was an attempt to target locations that are not well connected (i.e., its larvae end up in the same spot).

I've also since discovered that while its values are nominally bounded between 0 and 1, values below 0 are theoretically possible (and do appear in our case). 

To address this and for ease of interpretation I've switched to [betweenness centrality](https://neo4j.com/docs/graph-data-science/current/algorithms/betweenness-centrality/).

> The other key difference between the Matlab and Julia code for connectivity is that the Julia code does not use the digraph edge weights - the weights are commented out with the note that "commented out as ew_base are all equally weighted anyway".

From memory that was carried over from the original MATLAB implementation (at least in one of the branches), and as the comment suggests, output from `centrality()` in MATLAB with and without `ew_base` was identical.

> does this mean TP_base needs to be multiplied by area and coral cover every time step, as coral cover varies?
> Ideally, but I realise this would create an overhead.

Doesn't matter if we're fixing a bug. If you want the wrong answer really fast, I can write up something that does it much faster than what we have right now.

Incidentally @Rosejoycrocker what tests do we currently have that catches these issues? I'm somewhat surprised the bug managed to live this long.

**Comment by Rosejoycrocker** [comment]
> @Rosejoycrocker as I mentioned, the ReefMod related work was done on the `ADRIA-ReefMod` branch.
Yes, I only mentioned this because I don't imagine there is any difference in how the connectivity centrality criteria is calculated in the ReefMod branch and Main, unless I am mistaken?

Good work spotting the bug, we should definitly add a test for this kind of thing. The only test we currently have for connectivity is to make sure the site orders line up with site_ids.

> > does this mean TP_base needs to be multiplied by area and coral cover every time step, as coral cover varies?
> > Ideally, but I realise this would create an overhead.
> 
> Doesn't matter if we're fixing a bug. If you want the wrong answer really fast, I can write up something that does it much faster than what we have right now.

Sorry, what do you mean by this? The suggestion that TP_base needed to be multiplied by area and coral cover was one that Ken made in that email exchange titled "RME-ADRIA material"  first sent on Thursday 4/6/2023 3:53PM. I went in to the code to check what we were doing instead and made this issue.

**Comment by ConnectedSystems** [comment]
> Sorry, what do you mean by this?

It was a response to both of you. I'm saying taking a hit to computational performance because we're doing the "right" thing is always preferred to not doing the correct calculation but having the model run fast. So considering "overhead" shouldn't be a motivating factor.

**Comment by Rosejoycrocker** [comment]
Ah, I see. Sorry I thought you meant it was the wrong way to do it in "wrong answer really fast" 😆 Ok cool, I agree

**Comment by ConnectedSystems** [comment]
An update:

For the basic centrality measures (indegree, outdegree) results of a simple graph and a weighted graph are identical - these measures simply count the number of connected neighbors so that makes sense.

But for the more complicated measures, it's necessary to use a weighted graph - I should've realised that but I guess my attention was elsewhere.

@Rosejoycrocker 

I've reverted to simple indegree and outdegree for testing, setting out connectivity weights to 0 and in connectivity weights to 1.0 and am still seeing completely unconnected locations being selected (note Rank 1 and 3).

Truncated example selection:

|rank|index_id|times_top_ranked|rank_proportion_perc               |k_area|cover_2025|in_conn          |out_conn              |dhw                   |wave     |
|----|--------|----------------|-----------------------------------|------|----------|-----------------|----------------------|----------------------|---------|
|   1 |     762 |               4 |               25.0                |76535.61929551527 |0.00036992142664547654 |0.0                    |        0             |7.525906431402939     |0.7184263584277283|
|   2 |     780 |               4 |               25.0                |80295.96827898972 |0.0005456416045994108  |0.0001249414914568486  |    95702             |8.308089025317301     |0.5142337443942985|
|   3 |     842 |               4 |               25.0                |83152.23916691837 |0.0006502802911175124  |0.0                    |        0             |7.244507477496267     |0.45024059903655134|
|   4 |     898 |               5 |               31.25               |93815.09656798207 |0.0010966958830543007  |0.0007038013844283881  |368073713             |7.5524006456603825    |0.600217748197043|
|   5 |     923 |               4 |               25.0                |92246.81997960537 |0.0005152563150631169  |0.00033150544075004584 |   623184             |8.081236455598775     |0.9726745425442535|
|   6 |    3486 |               3 |               18.75               |68927.62644117688 |0.00037453302197554234 |4.378947829523027e-5   | 40876759             |7.6241699997853365    |0.5707272948566706|

When I look into it, it seems the algorithm is preferencing locations with larger k area, even if there are smaller locations that I feel should rank higher as `out_seed_connectivity` is set to 1.0

Compare the first two locations below. 

- The first is Rank 1 in the table above (index 762)
- the second an unselected location (index 822) which might be preferred instead.
- the third is an example of a location that is ignored because it is small, but has plenty of space, and is incredibly well connected.

Note DHWs are roughly comparable. Surely that's not what's dominating the rankings? (`heat_stress` is set to 0.8)

|k_area |cover_2025 |in_conn   |out_conn   |dhw    |wave    |
|-------|-----------|----------|-----------|-------|--------|
|76535.6|0.000369921|0.0       |0          |7.52591|0.718426|
|54981.9|0.000212647|6.51127e-5|81738595   |7.5524 |0.450241|
|13170.1|7.74109e-5 |0.131246  |52922491744|7.5524 |0.450241|

**Comment by Rosejoycrocker** [comment]
Thanks @ConnectedSystems . If you find the same thing again it could be an issue with the normalisation which I can look into. I'll  wait for your update though. Sorry I haven't been able to look into it myself. I had some issues getting the ReefMod scripts to run but haven't followed up on it yet because of trying to finish up the make mcda generic issue.

**Comment by KRNA01** [comment]
Hi @ConnectedSystems and @Rosejoycrocker 
Have we solved the issue of connection strengths in the MCDA?
Do you need my help?

**Comment by Rosejoycrocker** [comment]
Hi @KRNA01, Takuya and I spoke about it in todays meeting and we were wondering if TP_base*area could instead be used to calculate in_conn and out_conn. The overhead introduced by multiplying at each timestep could be large so we were trying to come up with alternatives. Another alternative is to only recalculate every 5 or 10 years. What do you think?

**Comment by ConnectedSystems** [comment]
I'm running some examples now to see what kind of difference it makes.

If we need to re-calculate connectivities every decision year, then in the worst case (simulating the most adaptive intervention policy) this could make ADRIA about 4 times slower than ReefMod if running GBR-scale simulations, but ADRIA would be much more informed. 

If that's what we need, then so be it.

That said, there may be alternative centrality measures that are easier to calculate and give comparable results. Won't know until I finish these runs.

**Comment by ConnectedSystems** [comment]
I'll email findings separately.

**Comment by ConnectedSystems** [comment]
Closing as I think this is resolved.

Reopen if you feel it hasn't been.
