### ISSUE TITLE
Order of scenarios plotted are inconsistent

### ISSUE THREAD

**Issue by ConnectedSystems** [open-AIMS/ADRIA.jl#769]
Scenario visualizations order scenario groupings based on variance.

This causes an artifact where plots do not maintain consistent ordering. It should always be "counterfactual", "unguided", "guided".

https://github.com/open-AIMS/ADRIA.jl/blob/437d51a030bd58f0d794dd46d03056a70f8fa09c/ext/AvizExt/viz/scenarios.jl#L221

**Comment by Zapiano** [comment]
@ConnectedSystems the idea behind that was that, if a plot has a big variance and it's on top of another with low variance, it will cover it and it will be hard to "read" the plot. 

Before I change this, just wanted to confirm that we want to keep a fixed/consistent order instead of adjusting based on variance.

**Comment by ConnectedSystems** [comment]
The functionality should be split.

When comparing sets of runs, you'd want the order to be consistent between figures, especially for reports and the like.

For scenario clustering I agree you want things to be reordered based on scenario cluster properties.
