### ISSUE TITLE
StackOverflowError in tests failing on main branch 

### ISSUE THREAD

**Issue by Zapiano** [open-AIMS/ADRIA.jl#890]
When I run the tests on the main branch I get a `ERROR: LoadError: StackOverflowError:`. The stacktrace is giant, but the relevant line seems to be ADRIA.jl\ext\AvizExt\viz\spatial.jl:152:

![image](https://github.com/user-attachments/assets/94a6fb8d-a622-412b-b766-fc035e1960ba)

**Comment by Zapiano** [comment]
@arlowhite @ConnectedSystems  FYI

**Comment by arlowhite** [comment]
Yep, the [last Unit Tests run](https://github.com/open-AIMS/ADRIA.jl/actions/runs/11455651032) failed
https://github.com/open-AIMS/ADRIA.jl/actions/workflows/UnitTests.yml?query=branch%3Amain

**Comment by ConnectedSystems** [comment]
Yeah, looking into it now ☹️

**Comment by ConnectedSystems** [comment]
The error is caused by calls to the following lines:

https://github.com/open-AIMS/ADRIA.jl/blob/32fa1684916d2dba1b37f0a8ea3b622f12029ba6/ext/AvizExt/viz/spatial.jl#L152-L155

```julia
reset_limits!(current_axis())
trim!(f)
resize_to_layout!(current_figure())
```

These are intended to: 
1. Ensure axis limits match that of the data (originally thought to be necessary as we may add data beyond the original axis when creating the figure)
2. Remove any empty subplots
3. Resize the final figure to match the figure size after empty plots were removed

Commenting out `reset_limits!()` and `resize_to_layout!()` allows all tests to pass.
Given the error that is thrown, I suspect one of the figure elements (which is an observed variable; @arlowhite this allows reactive code flows https://juliagizmos.github.io/Observables.jl/stable/) is updated and triggers a call to one or more of `current_axis()`, `reset_limits!()` or `resize_to_layout!()`, thereby causing an infinite loop, and then a stackoverflow.

Makie internals have changed a lot judging by the release notes so I'm looking into whether we need these method calls at all.

**Comment by ConnectedSystems** [comment]
I was wrong, it's something to do with `current_figure()` itself failing to render the image.

When I `infiltrate` into the test and try `current_figure()` I get:

```julia
Error showing value of type Figure:
ERROR: Not all have the same length: [:markersize => 0, :color => 4, :rotation => 4, :pos => 0, :quad_offset => 0, :uv_offset_width => 0, :marker_offset => 0]
```

Which suggests the underlying cause is some figure option.
